### ISSUE TITLE
Pull the Version Number from the Build that is being deployed.

### ISSUE THREAD

**Issue by SchulzDL** [renevanosnabrugge/vsts-promotepackage-task#2]
This is a nice task which allows me to promote my packages as they flow through the pipeline.  The only problem that I have is that I have to plug in the Version Number which is both a pain and a problem.  I would like to see an option within the task to pull the version number from the build that is being deployed in this pipeline.  I want to include it in my release pipeline so that after it is deployed and tested can be promoted to the next level.  In my Dev and QA environments, this would be promoting to PreRelease and the QA consuming only packages that are at least PreRelease.  Then after deployment to production promote it to Release.

**Comment by renevanosnabrugge** [comment]
You can use the default nuget tasks and the Build variables to achieve this. This task is purely for promoting .


Verstuurd vanaf mijn iPhone

Op 19 jun. 2017 om 18:51 heeft SchulzDL <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


This is a nice task which allows me to promote my packages as they flow through the pipeline. The only problem that I have is that I have to plug in the Version Number which is both a pain and a problem. I would like to see an option within the task to pull the version number from the build that is being deployed in this pipeline. I want to include it in my release pipeline so that after it is deployed and tested can be promoted to the next level. In my Dev and QA environments, this would be promoting to PreRelease and the QA consuming only packages that are at least PreRelease. Then after deployment to production promote it to Release.

**Comment by SchulzDL** [comment]
And that is what I am using the task for to Promote the NuGet package, however, I don’t want to have to enter the Version number because I should be able to get that from the package that I am promoting which was created in a build process.  This promotion task is part of a release pipeline and I don’t want to have to change the version number.

Donald Schulz
Senior ALM Consultant | Imaginet | MCTS TFS
dschulz@imaginet.com<mailto:dschulz@imaginet.com> | P: 972.607.4836 | C: 805-813-1829 | tw: @justimaginet<http://www.twitter.com/justimaginet> |fb: justimaginet<http://www.facebook.com/justimaginet>

**Comment by renevanosnabrugge** [comment]
I did not test this, but the dropdown with version is also available for adding your own. If you add te version number of the package there, (the same as you use to version your package) I think it might work.

**Comment by eugenpodaru** [comment]
@SchulzDL You can use the build.buildNumber variable for the package version. In my build definition I use GitVersion to set the buildNumber to the semver, and in my release pipeline I use the buildNumber as the package version.

See [here](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch) more predefined variables.
