### ISSUE TITLE
failed to list packages and views in newly created feeds 

### ISSUE THREAD

**Issue by zsw316** [renevanosnabrugge/vsts-promotepackage-task#38]
As far as I know, Microsoft changed the scope of Azure Artifacts feeds from sometime in Nov2019. By default, the newly created feeds are project-scoped, only when the project is made public, its scoped feeds become public. 

Details can be seen from https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/project-scoped-feeds?view=azure-devops 

Given that, this task needs to be updated to adapt to that change.

**Comment by rdayan1** [comment]
+1

**Comment by renevanosnabrugge** [comment]
I still see the feed in the project feed. Can you explain a bit more what you mean?

**Comment by wouterroos** [comment]
Hi,

I'm seeing a similar issue. Newly created feeds are automatically set as 'Project scoped' on creation (I can't seem to find a way to change this). The 'Release Views' dropdown in the step is not populated for these feeds. I also tried to manually enter the name of the desired view instead of selecting it but this causes the following error when executing the release:

```
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()at Get-FeedId, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.5\vsts-promotepackage-task.ps1: line 46
at Set-PackageQuality, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.5\vsts-promotepackage-task.ps1: line 135
at Run, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.5\vsts-promotepackage-task.ps1: line 280
at <ScriptBlock>, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.5\vsts-promotepackage-task.ps1: line 286
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1
```

**Comment by renevanosnabrugge** [comment]
Is the release views dropdown not populated in the project where the feed is created or another project ?

Verstuurd vanaf mijn iPhone

Op 18 dec. 2019 om 15:37 heeft Wouter Roos <notifications@github.com> het volgende geschreven:

﻿

Hi,

I'm seeing a similar issue. Newly created feeds are automatically set as 'Project scoped' on creation (I can't seem to find a way to change this). The 'Release Views' dropdown in the step is not populated for these feeds. I also tried to manually enter the name of the desired view instead of selecting it but this causes the following error when executing the release:

System.Net.WebException: The remote server returned an error: (404) Not Found.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()at Get-FeedId, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.5\vsts-promotepackage-task.ps1: line 46
at Set-PackageQuality, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.5\vsts-promotepackage-task.ps1: line 135
at Run, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.5\vsts-promotepackage-task.ps1: line 280
at <ScriptBlock>, D:\a\_tasks\rvo-vsts-promotepackage-task_7ca5869f-a901-4012-a50d-d0f9d436ffec\2.0.5\vsts-promotepackage-task.ps1: line 286
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1

**Comment by wouterroos** [comment]
Same project.

**Comment by renevanosnabrugge** [comment]
Ok. I managed to reproduce the issue. However, I feel it is an issue with the MS task lib.  https://github.com/microsoft/azure-pipelines-extensions/blob/master/docs/authoring/endpoints/tfs-vsts-endpoints.md

In the code I refer to 
"endpointId": "tfs:feed",
"endpointUrl": "{{endpoint.url}}/_apis/packaging/feeds",

Endpoint should contain the url with ""project" in it. If this is the case, it all works.. I am raising an issue with MS

**Comment by renevanosnabrugge** [comment]
https://github.com/microsoft/azure-pipelines-extensions/issues/755

**Comment by amrock-my** [comment]
Even if the feed url for the task.json was proper, the powershell script does not account for the adjustment in the url.

I created a local (private) copy of the extension for testing and it seems to work, with the exception that the release drop down still does not populate. I'll create a pull request so that the script itself at least works.

**Comment by amrock-my** [comment]
I'm  not sure how to go about contributing my changes, I don't seem to have permissions to create a new branch so that I can make a pull request.

**Comment by renevanosnabrugge** [comment]
Create a fork and make a PR

Thanks !!

Verstuurd vanaf mijn iPhone

Op 3 jan. 2020 om 15:30 heeft amrock-my <notifications@github.com> het volgende geschreven:

﻿

I'm not sure how to go about contributing my changes, I don't seem to have permissions to create a new branch so that I can make a pull request.

**Comment by DaRochaRomain** [comment]
I'm still having the issue. Any workaround?

**Comment by jessehouwing** [comment]
Fixed in the UI now too.

**Comment by renevanosnabrugge** [comment]
Fixed in 
https://github.com/renevanosnabrugge/vsts-promotepackage-task/pull/54

**Comment by wouterroos** [comment]
@renevanosnabrugge Great, thanks!
