### ISSUE TITLE
Allow 'Release Views' field to be parameterized

### ISSUE THREAD

**Issue by wouterroos** [renevanosnabrugge/vsts-promotepackage-task#7]
As the title states, it would be nice if the 'Release Views' field could be specified using a parameter. This would allow a collection of these tasks to be put into as task group and be re-used across release environments.

Thanks in advance!

**Comment by wouterroos** [comment]
Saw that this issue is closed, does this mean this functionality has been implemented?

Thanks!

**Comment by renevanosnabrugge** [comment]
No. I cannot find the time to implement iT. Sorry

Verstuurd vanaf mijn iPhone

Op 15 nov. 2018 om 20:57 heeft Wouter Roos <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Saw that this issue is closed, does this mean this functionality has been implemented?

Thanks!

**Comment by wouterroos** [comment]
Perhaps better to leave it open then?

**Comment by renevanosnabrugge** [comment]
Good point. I will re-open.

**Comment by renevanosnabrugge** [comment]
Solved by https://github.com/renevanosnabrugge/vsts-promotepackage-task/pull/14
