### ISSUE TITLE
Promote multiple packages to different views

### ISSUE THREAD

**Issue by rohithjidagam** [renevanosnabrugge/vsts-promotepackage-task#8]
I have a requirement where my build publishes multiple packages to the npm registry and msteams feed. The problem is I need to promote them to different views based on the build. (For Example: In CI build, the published packages needs to be promoted to Release view). I found that we can do this for a single package using this task: https://marketplace.visualstudio.com/items?itemName=rvo.vsts-promotepackage-task

But, I want to do it for multiple packages without wanting to have the task multiple times in my build. Any suggestions would be appreciated? Can this feature be enabled on this task?

**Comment by renevanosnabrugge** [comment]
Hi,

Not planned for this task. Maybe you can create a task group to reduce to 1 task

Of course I accept Pull Requests!

Thanks

Rene

Verstuurd vanaf mijn iPhone

Op 25 okt. 2018 om 20:44 heeft Rohith.Jidagam <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I have a requirement where my build publishes multiple packages to the npm registry and msteams feed. The problem is I need to promote them to different views based on the build. (For Example: In CI build, the published packages needs to be promoted to Release view). I found that we can do this for a single package using this task: https://marketplace.visualstudio.com/items?itemName=rvo.vsts-promotepackage-task<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmarketplace.visualstudio.com%2Fitems%3FitemName%3Drvo.vsts-promotepackage-task&data=02%7C01%7C%7C1b4eef1a303544a433f308d63aa9d9e1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636760898504640413&sdata=nfMLy6Z43S47lIJUxGkTXzU%2BpINEd0B3xP7YpabT8FI%3D&reserved=0>

But, I want to do it for multiple packages without wanting to have the task multiple times in my build. Any suggestions would be appreciated? Can this feature be enabled on this task?

**Comment by renevanosnabrugge** [comment]
not fixing
